name: R2 Backup
on:
  push:
    branches:
      - main
jobs:
  r2Backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: R2 Backup
        uses: JoseMoranUrena523/r2-backup@v1.0.0
        env:
          ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
        with:
          args: --overwrite --remove --md5 --exclude .git*
